// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBU4Mu8Dq1YkiJDHqAbDuHwc8q5JMVtO4',
    appId: '1:84595542956:android:897c98eec70aa34f524809',
    messagingSenderId: '84595542956',
    projectId: 'anayam-b4680',
    storageBucket: 'anayam-b4680.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDVAA3yvMHZuYKbodXCITkIWtHYF5920sw',
    appId: '1:84595542956:ios:21464a43fa8e5957524809',
    messagingSenderId: '84595542956',
    projectId: 'anayam-b4680',
    storageBucket: 'anayam-b4680.firebasestorage.app',
    iosBundleId: 'com.aastudio.burlaxatunapp',
  );
}
